### ISSUE TITLE
对相似度分数的看法

### ISSUE THREAD

**Issue by hailiang-wang** [yongzhuo/near-synonym#1]
看上去对同一组词， near-synonym 的分值更高，synonym 的分值低。

![screenshot_20240412144504](https://github.com/yongzhuo/near-synonym/assets/3538629/43fb8742-f61e-46b8-a29b-f1a6ad8e3481)

near-synonym 项目的技术比较新，如果有意愿维护 synonyms 库咱们可以聊聊。

https://github.com/chatopera/Synonyms

**Comment by yongzhuo** [comment]
最初的目的是为了区分近义词、反义词，没有太关注相似度
